//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.WcfReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WcfReference.IWcfService")]
    public interface IWcfService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/CheckIfPrimeNumber", ReplyAction="http://tempuri.org/IWcfService/CheckIfPrimeNumberResponse")]
        string CheckIfPrimeNumber(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/CheckIfPrimeNumber", ReplyAction="http://tempuri.org/IWcfService/CheckIfPrimeNumberResponse")]
        System.Threading.Tasks.Task<string> CheckIfPrimeNumberAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/AddDigits", ReplyAction="http://tempuri.org/IWcfService/AddDigitsResponse")]
        int AddDigits(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/AddDigits", ReplyAction="http://tempuri.org/IWcfService/AddDigitsResponse")]
        System.Threading.Tasks.Task<int> AddDigitsAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/ReverseString", ReplyAction="http://tempuri.org/IWcfService/ReverseStringResponse")]
        string ReverseString(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/ReverseString", ReplyAction="http://tempuri.org/IWcfService/ReverseStringResponse")]
        System.Threading.Tasks.Task<string> ReverseStringAsync(string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/PrintHtmlTag", ReplyAction="http://tempuri.org/IWcfService/PrintHtmlTagResponse")]
        string PrintHtmlTag(string tag, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/PrintHtmlTag", ReplyAction="http://tempuri.org/IWcfService/PrintHtmlTagResponse")]
        System.Threading.Tasks.Task<string> PrintHtmlTagAsync(string tag, string value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/SortNumbers", ReplyAction="http://tempuri.org/IWcfService/SortNumbersResponse")]
        int[] SortNumbers(int[] numbers, bool ascending);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IWcfService/SortNumbers", ReplyAction="http://tempuri.org/IWcfService/SortNumbersResponse")]
        System.Threading.Tasks.Task<int[]> SortNumbersAsync(int[] numbers, bool ascending);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IWcfServiceChannel : Client.WcfReference.IWcfService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WcfServiceClient : System.ServiceModel.ClientBase<Client.WcfReference.IWcfService>, Client.WcfReference.IWcfService {
        
        public WcfServiceClient() {
        }
        
        public WcfServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WcfServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WcfServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string CheckIfPrimeNumber(int value) {
            return base.Channel.CheckIfPrimeNumber(value);
        }
        
        public System.Threading.Tasks.Task<string> CheckIfPrimeNumberAsync(int value) {
            return base.Channel.CheckIfPrimeNumberAsync(value);
        }
        
        public int AddDigits(int value) {
            return base.Channel.AddDigits(value);
        }
        
        public System.Threading.Tasks.Task<int> AddDigitsAsync(int value) {
            return base.Channel.AddDigitsAsync(value);
        }
        
        public string ReverseString(string value) {
            return base.Channel.ReverseString(value);
        }
        
        public System.Threading.Tasks.Task<string> ReverseStringAsync(string value) {
            return base.Channel.ReverseStringAsync(value);
        }
        
        public string PrintHtmlTag(string tag, string value) {
            return base.Channel.PrintHtmlTag(tag, value);
        }
        
        public System.Threading.Tasks.Task<string> PrintHtmlTagAsync(string tag, string value) {
            return base.Channel.PrintHtmlTagAsync(tag, value);
        }
        
        public int[] SortNumbers(int[] numbers, bool ascending) {
            return base.Channel.SortNumbers(numbers, ascending);
        }
        
        public System.Threading.Tasks.Task<int[]> SortNumbersAsync(int[] numbers, bool ascending) {
            return base.Channel.SortNumbersAsync(numbers, ascending);
        }
    }
}
